
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?=$this->view->nome_usuario->nome?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_tweets?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->total_seguindo?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguidores?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form action="/tweet" method="post">
						<textarea class="form-control" name="texto_tweet" id="exampleFormControlTextarea1" rows="3"></textarea>
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>
            <?foreach($this->view->tweets as $values){?>
			<div class="row tweet">
				<div class="col">
					<p><strong><?=$values->nome?></strong> <span class="text text-muted"><?=$values->data?></span></p>
					<p><?=$values->tweets ?></p>

					<br />
					<?if($values->id_usuario == $_SESSION['id']){?>
					<form action="\remover" method="post" >
						<div class="col d-flex justify-content-end">
							<button type="submit" name="id_tweet" value="<?=$values->id?>" class="btn btn-danger"><small>Remover</small></button>
						</div>
					</form>
					<?}?>
				</div>
			</div>
            <?}?>
		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quemSeguir" class="quemSeguirTxt" >Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>